import React from 'react'

function About() {
    return (
        <div>
            <h3>About comp</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequuntur perferendis, exercitationem esse a placeat temporibus! Lorem ipsum dolor sit amet consectetur adipisicing elit. Consequatur at suscipit dicta aperiam excepturi itaque laudantium, aliquid aspernatur nemo ducimus perspiciatis assumenda. Quo atque optio illum alias nobis provident, minima recusandae dignissimos laudantium non magni vero voluptatem, saepe voluptate ratione totam fuga qui blanditiis culpa excepturi ut beatae ea in! Illo amet nam natus ratione dolor id facilis. Mollitia, voluptate accusamus provident ex voluptatum dolore omnis odit amet aspernatur earum! Officiis eos ipsum eius sit error, veniam tempora vero molestias sed excepturi! Eaque sequi autem architecto quo, officia natus repudiandae ea nostrum quis, pariatur iste eum qui fugiat, odit eos cum distinctio ex temporibus rerum impedit ab facere nobis? Sit natus eaque nobis nostrum sunt maxime temporibus quibusdam sequi veniam repellendus. Voluptates, excepturi, hic, eligendi maiores velit vel modi laborum odio nulla beatae inventore quam pariatur. Laborum, magnam molestiae dolore dolorum porro excepturi, corrupti odio sapiente ducimus voluptatum quo laudantium? Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque architecto officia dicta perspiciatis, illo, officiis explicabo atque aperiam praesentium repellendus eligendi est necessitatibus culpa ducimus accusamus veritatis. Hic ullam aperiam maiores perspiciatis fuga ipsum, eaque voluptas laborum! Saepe exercitationem ab aut iusto excepturi, accusamus, autem minima aliquam temporibus sequi deserunt! Autem earum optio quod nesciunt, repellendus facilis harum deserunt vitae dolores quas dolorum eos consequuntur dignissimos modi nostrum quidem necessitatibus laborum neque cupiditate laudantium? Id magnam eaque cumque architecto quas voluptate, quo aliquam suscipit nisi sunt officia enim nihil fuga amet omnis laborum perferendis. Eum, ullam fuga? Quibusdam, consectetur cum ab aperiam, veritatis consequatur, provident repudiandae officiis repellendus explicabo architecto? Error nulla magni cumque voluptates id, delectus ducimus. Totam ratione provident aliquam esse cumque modi fuga accusamus adipisci eum hic nobis atque architecto odit, nemo voluptas blanditiis placeat neque quidem qui aspernatur libero laborum reprehenderit assumenda! Sequi tempora eligendi fugit voluptatem blanditiis explicabo laborum fuga autem molestias incidunt et, excepturi iusto, libero dolorum nobis, rem deleniti. Fuga pariatur blanditiis consequatur modi obcaecati suscipit? Harum maiores ab modi at dolor. Optio ducimus corrupti ab nulla quis iusto officia? Dolorum obcaecati iste repudiandae unde natus libero, enim vel labore, itaque sunt tenetur.</p>
        </div>
    )
}

export default About
